# App Name
spring.application.name=payment-ledger

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_ledger_db
spring.datasource.username=postgres
spring.datasource.password=VarunKumar
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
