## App Name
#spring.application.name=payment-ledger
#
## Database Connection Settings
#spring.datasource.url=jdbc:postgresql://localhost:5432/payment_ledger_db
#spring.datasource.username=postgres
#spring.datasource.password=VarunKumar@#123
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA & Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# App Name
spring.application.name=payment-ledger

# Database Connection Settings
spring.datasource.url=postgresql://payment_ledger_db_user:vvmX9WUkAsNjm8994xblJSnVnXZVP8Sd@dpg-d8qe44u8bjmc738knkpg-a/payment_ledger_db
spring.datasource.username=payment_ledger_db_user
spring.datasource.password=vvmX9WUkAsNjm8994xblJSnVnXZVP8Sd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
